name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      pull-requests: write

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org' # 'https://npm.pkg.github.com'
    # Skip post-install scripts here, as a malicious
    # script could steal NODE_AUTH_TOKEN.
    - run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # `npm rebuild` will run all those post-install scripts for us.
    - run: npm rebuild && npm run prepare --if-present
    - run: npm test


